apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: whatsapp
  type: NodePort
  ports:
    - port: 8084         # external port
      targetPort: 8080  # must match containerPort
      nodePort: 30084    # optional - can be chosen automatically
