global:
    scrape_interval: 15s  # Default scrape interval

    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'sb-application'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:7031']  # <-- FIXED indentation
      labels:
          application: "my boot app"
